### PR TITLE
commit images for SC tutorial.

### PR DESCRIPTION
**Pull request by Joanone**

### CODE REVIEW

**Comment by stebo85** [comment]
wonderful - thank you :)

**Comment by Joanone** [comment]
You’re welcome :)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Joanone** [comment]
Hello Steffen, i just realised that the images i added are not visible from the direct tutorial page: 'https://www.neurodesk.org/tutorials-examples/tutorials/structural_imaging/structuralconnectivity/'. Can you see them from your end? or did i probably miss something?

**Comment by stebo85** [comment]
The path to the images is incorrect. Can you fix it?

**Comment by Joanone** [comment]
Oh I see.
Can you kindly give me steps on how to correct the path?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by stebo85** [comment]
Dear @Joanone,

I fixed it now. The problem was that the directory you put the image files in was not in the static sub-directory :)

Thank you
Steffen

**Comment by Joanone** [comment]
Dear Steffen,

My apologies. many thanks! And correction taken.

Kind regards,
Joan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Pull request merged**
