### PR TITLE
Fix neurodesk version templating

### PR DESCRIPTION
**Pull request by stebo85**
@iishiishii - I noticed that no version was displayed and that the hostname wasn't in the example startups yet, so I tried to fix it.

### CODE REVIEW

**Comment by stebo85** [comment]
that didn't work:

Error: Error building site: "/home/runner/work/neurodesk.github.io/neurodesk.github.io/content/en/docs/Getting Started/Storage/_index.md:48:183": failed to extract shortcode: template for shortcode "params/neurodesktop/jupyter_neurodesk_version" not found

@iishiishii or @aswinnarayanan  do you see why?

**Comment by aswinnarayanan** [comment]
I know what's causing this, will fix shortly

**Comment by aswinnarayanan** [comment]
@iishiishii @stebo85 

{{< params/neurodesktop/***>}} doesn't reference data/neurodesktop.toml 

It is looking for name-matched shortcode templates under [layouts/shortcodes/params/neurodesktop/](https://github.com/NeuroDesk/neurodesk.github.io/tree/main/layouts/shortcodes/params/neurodesktop/)

The shortcode template is the one referencing neurodesktop.toml file. 
(`{{ .Site.Data.neurodesktop }}` is `data/neurodesktop.toml`)

**Comment by stebo85** [comment]
oh, good to know! Thank you for fixing it and for documenting this in the toml file :)

**Pull request merged**
