### PR TITLE
grouping the main items in related groups 

### PR DESCRIPTION
**Pull request by stebo85**
(access, community, components)

### CODE REVIEW

**Review by aswinnarayanan — CHANGES_REQUESTED** [review]
Hi @stebo85. This grouping makes more sense. But I think it's affects the discoverability a bit. What do you think about dividing it this way?
image

**Comment by aswinnarayanan** [comment]
This is just for the short term. With the list of features and key pages increasing, we may need to switch to a different style for the feature list in future, probably one with the groupings suggested

**Comment by stebo85** [comment]
Ok, let's try your suggestion and see how it behaves on ipad / phone screens?

**Comment by stebo85** [comment]
awesome :) I think it's good!

image

thank you
Steffen

**Pull request merged**
