### PR TITLE
Edit landing page

### PR DESCRIPTION
**Pull request by iishiishii**
Open link in new tab.
Component card into row in mobile view.
Fix navbar.
Adjust margin for mobile.
Responsive font size.
Add favicon.

### CODE REVIEW

**Comment by aswinnarayanan** [comment]
Hi @iishiishii. The redesigned landing page looks great!!! Amazing work.

Could we add the quickstart buttons just for Linux MacOS and Windows? Just checking if it would affect any other changes you're planning.

**Comment by stebo85** [comment]
Dear @aswinnarayanan - I argued to keep the quickstart very clean, but I agree that we could add Linux, Mac and Windows back in - the rest of the site is now so nice and clean that I think we can afford more buttons :)

**Comment by aswinnarayanan** [comment]
Agreed. It looks much cleaner now.
I've added the three buttons

**Comment by stebo85** [comment]
image
Looks nice now my screen :)

**Pull request merged**
