### PR TITLE
Formatting fixes

### PR DESCRIPTION
**Pull request by aswinnarayanan**
- Update all code blocks to markdown code fences
- Spell check and fix spelling
- Fix broken links
- Switch to prismjs dark theme

### CODE REVIEW

**Comment by stebo85** [comment]
that looks great :) Is it on purpose that there is no syntax highlighting anymore :?

**Comment by aswinnarayanan** [comment]
Thanks @stebo85. My mistake, I've added back the syntax highlighting now

**Comment by stebo85** [comment]
oh, cool! Thank you - looks fantastic now :) Now we just need to fix a few littel code blocks that have the incorrect naming. I love the markdown style now. The old way didn't render nicely on github, but now it's nice on every platform.

**Comment by aswinnarayanan** [comment]
Yeah, the old method got a bit messy. This should be a lot simpler going forward.

Just putting down a note here...

I think we should switch from prismjs to chroma (hugo's included syntax highlighter) once the docsy team adds the copy button to the chroma renderer. Tracking this issue here. https://github.com/google/docsy/issues/1267

Chroma has a github-dark theme, it looks really good and will keep the site looking very consistent.

**Comment by stebo85** [comment]
ahh, great! Yes, the copy button is a crucial feature :D

**Pull request merged**
