### PR TITLE
Update Troubleshooting.md

### PR DESCRIPTION
**Pull request by civier**
An important issue with special characters interfering with copy and paste

### CODE REVIEW

**Review by stebo85 — APPROVED** [review]
oh wow - great find! could you test if this only for rdp? this might work via vnc

**Comment by civier** [comment]
> oh wow - great find! could you test if this only for rdp? this might work via vnc

I do not have a neurodesktop with VNC setup at the moment, unfortunately.

But I can give you these pieces of information:
- It even affects copying stuff WITHIN neurodesktop (e.g., from the web browser inside neurodesktop to the terminal inside neurodesktop)
- Seems to be fine in the ARDC virtual desktop

**Comment by stebo85** [comment]
So it's only in the docker version with rep?

**Comment by civier** [comment]
Yep. AFAIK

**Comment by civier** [comment]
BTW, despite you approving the commit, I do not see here the new text:
https://www.neurodesk.org/docs/neurodesktop/troubleshooting/
In the past approved commits were showing up immediately. Has
something changed? Or am I missing something?

Best,
Oren

**Comment by stebo85** [comment]
Because it's not merged yet. Doing that now.

**Comment by stebo85** [comment]
I just tested a bit more with this: It affects VNC and RDP. I open an issue to track this.

**Pull request merged**
