### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by civier**
Added my contributions. Because it's a long list, I moved my name to the end (to be fair to the other contributors).

### CODE REVIEW

**Review by stebo85 — COMMENTED** [review]
@civier - many of these are not quite true and vastly overstate your contribution - are you sure about this? If this is how you perceive your contributions I think we should discuss in person to clarify.

@aswinnarayanan, @TomEmotion  what do you think?

**Comment by stebo85** [comment]
I would propose the following as contributions:

- https://github.com/civier
- Funding: ARDC Australian Electrophysiology Data Analytics PlaTform (AEDAPT) (CI for $566k AUD) - contributing to initial conceptualisation, EOI writeup, scope of project, proposal writeup, teaming up with the Australian Imaging Service (AIS), recruiting collaborators, assisting collaborators with case studies
- Design: piloting and evaluating existing solutions (e.g., CVL/ACCS)
- Design: leading the Virtual Neuro Machine (VNM) hackathon project in the 2020 OHBM BrainHack, where the first version of Neurodesktop was developed
- Development: allowing Neurodesk containers running in Neurodesktop to access sshfs mounts
- Development: template for container recipe documentation
- Development: software application containers - developer (bidscoin, MATLAB; in progress: MMVT)
- Development: software application containers - facilitator (Fieldtrip, running arbitrary scripts using compiled MATLAB containers; in progress: SOVABIDS)
- Documentation: for developers (contribution to "add tools", configuring Github)
- Documentation: for users (copy and paste troubleshooting, accessing storage, installation on different platforms, using ARDC Virtual Desktop Service, screenshots)
- Documentation: Neurodesk's original logo
- User testing: HPC, NECTAR, Mac, Linux, ARDC Virtual Desktop Service
- User testing: VNC and RDP interfaces, including multiple concurrent users
- User testing: running containers as sandboxes on HPC
- User testing: running Neurodesktop for long periods
- Outreach: initiating a user survey and analysing its results (2020)
- Outreach: taking part in a presentation for the Australian National Imaging Facility 2020
- Outreach: leading the AEDAPT project in BrainHack Global 2021
- Outreach: contributing to the ARDC TechTalk 2022 "Neurodesk and Neurodesktop: Software containers and CVMFS for low-maintenance, application-rich and FAIR desktop environment on PC, cloud or HPC"
- Outreach: presentations in conferences (2nd author eResearch 2020; 2nd author OHBM 2021; co-author eResearch 2021; co-author Australasian Cognitive Neuroscience Society 2021)
- Outreach: providing assistance to nodes of the Australian National Imaging Facility with installing/using Neurodesk 
- Administration: managing NECTAR resources allocated to the AEDAPT project
- Administration: maintaining contacts with AEDAPT project collaborators
- Administration: one of Neurodesk/AEDAPT representatives in ARCOS, AIS and NECTAR Interactive Analytics committees and working groups
- Papers: co-author Neurodesk manuscript (in preparation; contribution to initial outline, input on first draft), co-author proceedings of the OHBM Brainhack 2021 (to be published in Aperture)

**Comment by aswinnarayanan** [comment]
This is a different template for contributions compared to the existing one.
If this format is being proposed, I think we need to do this as a template change for the contributors page.

**Comment by aswinnarayanan** [comment]
We can set guidelines to maintain the template and formatting of the contributors page. 

I propose we impose the following. Each contributor entry consists of
1. Name
2. Github handle (or alternative org if unavailable)
3. Contribution description to Neurodesk as bullet point list limited to
   a. 12 bullet points
   b. 120 words

And we'll sort the contributors on the page how its currently sorted - based on the metrics on the github insights

@civier @stebo85 @TomEmotion 
Does this sound like a suitable set up?
If this is okay, I can update the contributors page with these guidelines.

**Comment by civier** [comment]
> @civier - many of these are not quite true and vastly overstate your contribution - are you sure about this? If this is how you perceive your contributions I think we should discuss in person to clarify.
> 
> @aswinnarayanan, @TomEmotion what do you think?

Dear @stebo85,
This is indeed how I perceive my contributions, and I do not agree with your statement that many of the things I listed are not quite true and vastly overstated. I will be happy to continue discussing it, but I'm afraid it will have to wait until Tom has time to attend the matter. He has a lot on his plate when returning from leave next week, so that might take some time.

**Comment by stebo85** [comment]
I am closing this pull request here and I added a contributions list that summarizes the important and relevant contributions from my perspective to the project trying to stay within reasonable length limits.

**Pull request closed without merging**
