### PR TITLE
Update storage.md

### PR DESCRIPTION
**Pull request by civier**
Clarified where the files are to be found after uploading to Neurodesktop using drag and dorp

### CODE REVIEW

**Comment by aswinnarayanan** [comment]
Thanks @civier. Steffen had configured guacamole in neurodesktop to use desktop as the drive path ([link](https://github.com/NeuroDesk/neurodesktop/blob/dfb05b27178631172a0fe1c164fc81048d8b742c/config/startup.sh#L108))

Just realised from your pull request (thanks) that the nectar desktop is using the guacmole default (`/home/vdiuser/thinclient_drives/GUACFS`)
Maybe we should get in touch with the nectar team and see if we can use desktop as well.

**Comment by stebo85** [comment]
is there an update on this? Is it now changed to the desktop on nectar's VDI service?

**Comment by stebo85** [comment]
closed because the pull request is out-dated by now.

**Comment by aswinnarayanan** [comment]
Will leave neurodesktop behaviour as is. Difference is due to specifics on the VDI deployment

**Pull request closed without merging**
